plugin:
  name: Example plugin
  codename: example-plugin

buckets:
  default-bucket:
    access: common
    type: list
    encrypt: false

triggers:
  commands:
    - name: echo-command
      command: echo
      method: example.echo
      help: This command will reply same message what you send for.
      args:
        text: "Вы ничего не написали...:str"
  scheduled:
    - name: every_minute
      time: "* * * * *"
      method: example.echo
      args:
        text: "Minute is gone"
  ai_tools:
    - name: current_time_aitool
      method: example.get_time
      description: "This method return current time"
  api_endpoints:
    - name: echo_api
      method: example.echo
      args:
        text: str
      endpoint: "echo/<text>"
