project:
  name: Example project
  codename: example-project

buckets:
  default-bucket:
    access: common # can be common or personal
    type: list     # can be list or dict
    encrypt: false # can be false or true, default false

triggers:
  cmd:
    - command: echo
      method: example.echo
      args:
        text: str
  sch:
    - name: every_minute
      time: "* * * * *"
      method: example.echo
      args:
        text: "Minute is gone"
  ait:
    - name: current_time_aitool
      method: example.get_time
      description: "This method return current time"
  api:
    - name: echo_api
      method: example.echo
      args:
        text: str
      endpoint: "echo/<text>"
