plugin:
  name: Example plugin
  codename: example-plugin
  description: This plugin is just example, but it works.

bukcets:
  - codename: rights

triggers:
  commands:
    - name: Echo command
      help: Repeats the given text
      command: echo
      method: main.echo
      args:
        text: {d: "Вы не написали текст...", t: str}    
    