plugin:
  name: Example plugin
  codename: example-plugin
  description: This is example module

buckets:
  - codename: rights
  - codename: default-bucket
    access: common
    type: list
    encrypt: false

triggers:
  specific:
    init: example.init
  
  commands:
    - name: echo-command
      command: echo
      method: example.echo
      help: This command will reply same message what you send for.
      args:
        text: "Вы ничего не написали...:str"
    - name: Echo with joke
      command: sepc-echo
      method: example.spec-echo
      help: This command will reply same message what you send for but it need right.
      args:
        text: "Вы ничего не написали...:str"
      rights: [specific-right]
  scheduled:
    - name: every_minute
      time: "* * * * *"
      method: example.echo
      args:
        text: "Minute is gone"
  ai_tools:
    - name: current_time_aitool
      method: example.get_time
      description: "This method return current time"
  api_endpoints:
    - name: echo_api
      method: example.echo
      args:
        text: str
      endpoint: "echo/<text>"
